using Microsoft.AspNetCore.Mvc;

using GTRC_Basics.Models;
using GTRC_Database_API.Services;
using GTRC_Basics.Models.DTOs;
using GTRC_Basics;

namespace GTRC_Database_API.Controllers
{
    [ApiController]
    [Route(nameof(Entry))]
    public class EntryController(EntryService service, BaseService<Entry> baseService, FullService<Entry> fullService) : BaseController<Entry>(baseService, fullService)
    {
        [HttpPut("Get/ByUniqProps/0")] public async Task<ActionResult<Entry?>> GetByUniqProps(EntryUniqPropsDto0 objDto)
        {
            UniqPropsDto<Entry> _objDto = new() { Index = 0, Dto = objDto };
            Entry? obj = await service.GetByUniqProps(_objDto);
            if (obj is null) { return NotFound(obj); }
            else { return Ok(obj); }
        }

        [HttpPut("Get/ByProps")] public async Task<ActionResult<List<Entry>>> GetByProps(EntryAddDto objDto)
        {
            AddDto<Entry> _objDto = new() { Dto = objDto };
            return Ok(await service.GetByProps(_objDto));
        }

        [HttpPut("Get/ByFilter")] public async Task<ActionResult<List<Entry>>> GetByFilter(EntryFilterDtos objDto)
        {
            FilterDtos<Entry> _objDto = new() { Dto = objDto };
            return Ok(await service.GetByFilter(_objDto.Filter, _objDto.FilterMin, _objDto.FilterMax));
        }

        [HttpGet("Get/Temp")] public async Task<ActionResult<Entry?>> GetTemp()
        {
            Entry? obj = await service.GetTemp();
            if (obj is null) { return BadRequest(obj); }
            else { return Ok(obj); }
        }

        [HttpPost("Add")] public async Task<ActionResult<Entry?>> Add(EntryAddDto objDto)
        {
            Entry? obj = objDto.Dto2Model();
            bool isValid = service.Validate(obj);
            bool isValidUniqProps = await service.ValidateUniqProps(obj);
            if (obj is null) { return BadRequest(obj); }
            else if (!isValidUniqProps) { return StatusCode(208, obj); }
            else if (!isValid) { return StatusCode(406, obj); }
            else
            {
                await service.Add(obj);
                UniqPropsDto<Entry> uniqPropsDto = new();
                uniqPropsDto.Dto.Model2Dto(obj);
                obj = await service.GetByUniqProps(uniqPropsDto);
                if (obj is null) { return NotFound(obj); }
                else { return Ok(obj); }
            }
        }

        [HttpPut("Update")] public async Task<ActionResult<Entry?>> Update(EntryUpdateDto objDto)
        {
            Entry? obj = await service.GetById(objDto.Id);
            if (obj is null) { return NotFound(obj); }
            else
            {
                obj = objDto.Dto2Model(obj);
                bool isValid = service.Validate(obj);
                bool isValidUniqProps = await service.ValidateUniqProps(obj);
                if (obj is null) { return BadRequest(await service.GetById(objDto.Id)); }
                else if (!isValidUniqProps) { return StatusCode(208, obj); }
                else if (!isValid) { return StatusCode(406, obj); }
                else
                {
                    await service.Update(obj);
                    await fullService.UpdateChildObjects(typeof(Entry), obj);
                    return Ok(obj);
                }
            }
        }

        [HttpGet("Get/AutoGeneratedRaceNumbers/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetAutoGeneratedRaceNumbers(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            else { return Ok(await service.GetAutoGeneratedRaceNumbers(season.Id)); }
        }

        [HttpGet("Update/RaceNumbers/{seasonId}")] public async Task<ActionResult<List<Entry>>> UpdateRaceNumbers(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            else { return Ok(await service.UpdateRaceNumbers(season.Id)); }
        }
    }
}
