using Microsoft.AspNetCore.Mvc;

using GTRC_Basics.Models;
using GTRC_Database_API.Services;
using GTRC_Basics.Models.DTOs;

namespace GTRC_Database_API.Controllers
{
    [ApiController]
    [Route(nameof(Entry))]
    public class EntryController(EntryService service, BaseService<Entry> baseService, FullService<Entry> fullService) : BaseController<Entry>(baseService, fullService)
    {
        [HttpPut("Get/ByUniqProps/0")] public async Task<ActionResult<Entry?>> GetByUniqProps(EntryUniqPropsDto0 objDto)
        {
            UniqPropsDto<Entry> _objDto = new() { Index = 0, Dto = objDto };
            Entry? obj = await service.GetByUniqProps(_objDto);
            if (obj is null) { return NotFound(obj); }
            else { return Ok(obj); }
        }

        [HttpPut("Get/ByProps")] public async Task<ActionResult<List<Entry>>> GetByProps(EntryAddDto objDto)
        {
            AddDto<Entry> _objDto = new() { Dto = objDto };
            return Ok(await service.GetByProps(_objDto));
        }

        [HttpPut("Get/ByFilter")] public async Task<ActionResult<List<Entry>>> GetByFilter(EntryFilterDtos objDto)
        {
            FilterDtos<Entry> _objDto = new() { Dto = objDto };
            return Ok(await service.GetByFilter(_objDto.Filter, _objDto.FilterMin, _objDto.FilterMax));
        }

        [HttpGet("Get/Temp")] public async Task<ActionResult<Entry?>> GetTemp()
        {
            Entry? obj = await service.GetTemp();
            if (obj is null) { return BadRequest(obj); }
            else { return Ok(obj); }
        }

        [HttpPost("Add")] public async Task<ActionResult<Entry?>> Add(EntryAddDto objDto)
        {
            Entry? obj = objDto.Dto2Model();
            bool isValid = service.Validate(obj);
            bool isValidUniqProps = await service.ValidateUniqProps(obj);
            if (obj is null) { return BadRequest(obj); }
            else if (!isValidUniqProps) { return StatusCode(208, obj); }
            else if (!isValid) { return StatusCode(406, obj); }
            else
            {
                await service.Add(obj);
                UniqPropsDto<Entry> uniqPropsDto = new();
                uniqPropsDto.Dto.Model2Dto(obj);
                obj = await service.GetByUniqProps(uniqPropsDto);
                if (obj is null) { return NotFound(obj); }
                else { return Ok(obj); }
            }
        }

        [HttpPut("Update")] public async Task<ActionResult<Entry?>> Update(EntryUpdateDto objDto)
        {
            Entry? obj = await service.GetById(objDto.Id);
            if (obj is null) { return NotFound(obj); }
            else
            {
                obj = objDto.Dto2Model(obj);
                bool isValid = service.Validate(obj);
                bool isValidUniqProps = await service.ValidateUniqProps(obj);
                if (obj is null) { return BadRequest(await service.GetById(objDto.Id)); }
                else if (!isValidUniqProps) { return StatusCode(208, obj); }
                else if (!isValid) { return StatusCode(406, obj); }
                else
                {
                    await service.Update(obj);
                    await fullService.UpdateChildObjects(typeof(Entry), obj);
                    return Ok(obj);
                }
            }
        }

        [HttpGet("Get/AutoGeneratedRaceNumbers/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetAutoGeneratedRaceNumbers(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetAutoGeneratedRaceNumbers(season.Id));
        }

        [HttpGet("Update/RaceNumbers/{seasonId}")] public async Task<ActionResult<List<Entry>>> UpdateRaceNumbers(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            List<Entry> entriesToBeUpdated = await service.GetToBeUpdatedRaceNumbers(season.Id);
            bool isBadRequest = false;
            bool is208 = false;
            bool is406 = false;
            foreach (Entry obj in entriesToBeUpdated)
            {
                int id = obj.Id;
                bool isValid = service.Validate(obj);
                bool isValidUniqProps = await service.ValidateUniqProps(obj);
                if (obj is null) { isBadRequest = true; }
                else if (!isValidUniqProps) { is208 = true; }
                else if (!isValid) { is406 = true; }
                else { await service.Update(obj); await fullService.UpdateChildObjects(typeof(Entry), obj); }
            }
            if (isBadRequest) { return BadRequest(entriesToBeUpdated); }
            else if (is208) { return StatusCode(208, entriesToBeUpdated); }
            else if (is406) { return StatusCode(406, entriesToBeUpdated); }
            else { return Ok(entriesToBeUpdated); }
        }

        [HttpGet("Get/ByUserSeason/{userId}/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetByUserSeason(int userId, int seasonId)
        {
            User? user = await fullService.Services[typeof(User)].GetById(userId);
            if (user is null) { return NotFound(new List<Entry>()); }
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetByUserSeason(user, season));
        }
        
        [HttpGet("Get/ByUserEvent/{userId}/{eventId}")] public async Task<ActionResult<List<Entry>>> GetByUserEvent(int userId, int eventId)
        {
            User? user = await fullService.Services[typeof(User)].GetById(userId);
            if (user is null) { return NotFound(new List<Entry>()); }
            Event? _event = await fullService.Services[typeof(Event)].GetById(eventId);
            if (_event is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetByUserEvent(user, _event));
        }
        
        [HttpGet("Get/CarChangeCount/{entryId}/{eventId}")] public async Task<ActionResult<byte>> GetCarChangeCount(int entryId, int eventId)
        {
            Entry? entry = await fullService.Services[typeof(Entry)].GetById(entryId);
            if (entry is null) { return NotFound(byte.MinValue); }
            Event? _event = await fullService.Services[typeof(Event)].GetById(eventId);
            if (_event is null) { return NotFound(byte.MinValue); }
            if (entry.SeasonId != _event.SeasonId) { return StatusCode(406, byte.MinValue); }
            return Ok(await service.GetCarChangeCount(entry, _event));
        }
        
        [HttpGet("Get/DateLatestCarChange/{entryId}")] public async Task<ActionResult<DateTime>> GetDateLatestCarChange(int entryId, DateTime date)
        {
            Entry? entry = await fullService.Services[typeof(Entry)].GetById(entryId);
            if (entry is null) { return NotFound(byte.MinValue); }
            return Ok(await service.GetDateLatestCarChange(entry, date));
        }

        [HttpGet("Get/Violations/MinDriversPerEntryEvent/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetViolationsMinDriversPerEntryEvent(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetViolationsMinDriversPerEntryEvent(season));
        }

        [HttpGet("Get/Violations/MaxDriversPerEntryEvent/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetViolationsMaxDriversPerEntryEvent(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetViolationsMinDriversPerEntryEvent(season, true));
        }

        [HttpGet("Get/Violations/AllowDriverLineupPerEvent/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetViolationsAllowDriverLineupPerEvent(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetViolationsAllowDriverLineupPerEvent(season));
        }

        [HttpGet("Get/Violations/DateStartRegistration/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetViolationsDateStartRegistration(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetViolationsDateStartRegistration(season));
        }

        [HttpGet("Get/Violations/DateEndRegistration/{seasonId}")] public async Task<ActionResult<List<Entry>>> GetViolationsDateEndRegistration(int seasonId)
        {
            Season? season = await fullService.Services[typeof(Season)].GetById(seasonId);
            if (season is null) { return NotFound(new List<Entry>()); }
            return Ok(await service.GetViolationsDateStartRegistration(season, true));
        }
    }
}
